sudo: true
services:
  - docker

before_install:
  - docker pull ptpadan1246/amazonlinux_ansible
  - docker pull centos:6

script:
  - docker build -f docker/Dockerfile-centos -t centos .
  - docker build -f docker/Dockerfile-amazone -t amazone .

notifications:
  slack:
    secure: B3lzEeEKjKDb8upDdU9WUat6tGNBDEmC83PI25H6bxnWRDrJkPl1yPuBqVbXiu9gLQ1iR+gjJEYogu6m7eQHy7KNygsJUjlKjkS/g39sig+o3h3YjwitfaRWFPI3hfjaI21yUTuvJRKvtREACCQLPxdo6cDsHeVLiagPMyO/3/aJelw/w0Y4F6xDt4T/sypbowsxGl9Q2v9bTCrQcSi4V50dNUFlAKSiay00BKwEQ05RZ73skc/OESR9vW3xenCZLfc4ssS0Gb4SkwYT3F3qVF+liYET246OKhr/4k+cfGMcZ0mtSCCkTYhgBoUZPlN/I2MMEZka39Cr7XofOSToYMPJoeMOcHN2ZGAYFwMFEXKYqyb5EepNHM38nGJ2NsjpWvrdbgIfV7ouvZZ7KeHTJhF91V1H47lc2qI+Hizh10UiSiGlIcwNehUdbeu0tLxKWTBA4LR0+3T4FUpfRwBzHQU++lUr9Y8FM/reTBn6WL+pC2AE9yNzAWZMJYOZq2bBCczyGGFzfzSwMQFbYUhM+TkKgtiC7MrTKHfXYhEU8ywgYmbz/UuI0Ea96JJRsRbU9TPBqtwkpY7et9Jv8mWRj20unfUEQaiqnrqfsWVax+478gu1yDELJYnI48rR+6GZEVlJUsMnnnZ+lf2Upp6+9e3lPwiYtbt/EdDAyqm5T3M=
